<?php
/*
|----------------------------------------------------------------
| Application Settings - DO NOT CHANGE
|----------------------------------------------------------------
|
| All these settings are automatically configured and set
| to be accessed throughout the application - they do not need
| to be changed or tampered. This can be done within site.php
|
*/

/*
|----------------------------------------------------------------
| The directory in which the application resides
|----------------------------------------------------------------
|
| This is automatically generated, you can access this
| as a constant anywhere throughout the application
|
*/
	$settings[ 'DIRECTORY' ] = str_replace ( $_SERVER[ 'DOCUMENT_ROOT' ], '', DR ).'/';


/*
|----------------------------------------------------------------
| This is the absolute path of where the application resides
|----------------------------------------------------------------
|
| This is a combination of the directory and document root
| again this is accessible via a constant anywhere throughout
| the application
|
*/
	$settings[ 'PATH' ] = $_SERVER[ "DOCUMENT_ROOT" ] . $settings[ 'DIRECTORY' ];


/*
|----------------------------------------------------------------
| The IP of where the application resides
|----------------------------------------------------------------
|
| This is a constant that is accessibly anywhere throughout
| the application - automatically generated by the server details
|
*/
	$settings[ 'IP' ] = $_SERVER['HTTP_HOST'];


/*
|----------------------------------------------------------------
| The status of the application
|----------------------------------------------------------------
|
| Boolean choice between development & production environment
|
| This is defaulted to true, otherwise if the IP is local 
| the application knows it is on a local environment
|
*/
	$settings[ 'LIVE' ] = TRUE;

	if ($_SERVER['HTTP_HOST'] == 'localhost:8888' || substr($settings['IP'], 0, 7) == '192.168') {
		$settings[ 'LIVE' ] = FALSE;
	}


/*
|----------------------------------------------------------------
| The environment definition
|----------------------------------------------------------------
|
| This is generated by the result of the status of the application.
| Accessible anywhere throughout the application as a constant
|
*/
	$settings[ 'ENV' ] = ($settings['LIVE'] == FALSE ? 'development' : 'production');


/*
|----------------------------------------------------------------
| Defines the image path - either root to images or compressed
|----------------------------------------------------------------
|
| Images are compressed upon deployment, this is generated by the status
| of the environemnt and accessible as a constant anywhere throughout the
| application to reference the correct destination of images
|
*/
	$settings[ 'IMG_PATH' ] = ($settings['ENV'] == 'development' ? '' : 'compressed/');


?>